ignore:
  - "**/migrations"
  - "**/tests"
  - "**/tests.py"
  - "**/urls.py"
  - "**/wsgi.py"
  - "**/asgi.py"
  - "**/settings.py"
  - "**/admin.py"
  - "**/manage.py"
  - "**/apps.py"
  - "**/parsers"
