services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/project/frontend
      - /project/frontend/node_modules
    ports:
      - "3000:3000"
    command: sh -c "bun dev"
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      target: ${BUILD_TARGET}
    volumes:
      - ./backend:/project/backend
      - static_volume:/project/backend/django_static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      target: ${BUILD_TARGET}
    volumes:
      - static_volume:/project/backend/django_static/
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  celery:
    container_name: celery
    build:
      context: ./backend
      target: ${BUILD_TARGET}
    env_file:
      - .env
    command: celery -A core.celery.app worker -l debug
    depends_on:
      - redis
      - postgres
      - backend
    networks:
      - app-network

  celery-beat:
    container_name: celery-beat
    build:
      context: ./backend
      target: ${BUILD_TARGET}
    env_file:
      - .env
    command: celery -A core.celery.app beat -l debug
    depends_on:
      - redis
      - postgres
      - backend
      - celery
    networks:
      - app-network

  flower:
    container_name: flower
    build:
      context: ./backend
      target: ${BUILD_TARGET}
    command: celery -A core.celery.app flower -l debug
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - backend
      - celery
      - celery-beat
    networks:
      - app-network


volumes:
  static_volume:

networks:
  app-network:
    driver: bridge
